### ISSUE TITLE
distutils has been deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [django-ses/django-ses#232]
https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/django-ses/django-ses/blob/280ec80d0dc59ef6e5af2468982d1e3a03a52e08/setup.py#L8

Probably this code snippet could be vendored

https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/distutils/util.py#L110

**Comment by pcraciunoiu** [comment]
@tirkarthi if you'd like to submit a PR with details and a proposed fix, I can review it.

**Comment by mlissner** [comment]
I briefly studied the setup.py file. I could be off base, but my impression is that there's a fair bit of boiler plate in there that could be reduced or removed by moving to more modern packaging. 

For the packages my organization maintains, we usually use poetry, which does away with the setup.py and requirements.txt files and replaces them with a pyproject.toml file that holds all the needed metadata for the package. 

I know I'm pushing for another big swap in #182, so maybe I'm becoming a bit of a gadfly, but if you'd welcome a switch to poetry, I think I'd be able to put together a PR for it and I think it'd be a nice leap forward for the project. 

For example, building and uploading a package to pypi is much simpler. It's just:

```
poetry publish --build
```

This Github Action would do it on any commit tagged with v*.*.*:

```yaml
name: PyPI
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Publish to pypi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: "${{ secrets.pypi_token }}"
```
